### PR TITLE
Decorator as class property fails with babel@7

### PR DESCRIPTION
**Pull request by tylerturdenpants**
This blows up:

```javascript
  class Foo {
    @decorator(123)
    bar = 'baz'

  }
```

### CODE REVIEW

**Comment by tylerturdenpants** [comment]
and I have added the fix here as well

**Comment by pzuraq** [comment]
Awesome! Thanks so much for doing this 👍

**Comment by tylerturdenpants** [comment]
You’re welcome. I love doing this stuff!

**Comment by pzuraq** [comment]
Published in 2.1.1

**Pull request merged**
