### PR TITLE
Fix parallel

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by pzuraq** [comment]
Looks like the CLI upgrade broke some things, I'll see if I can check out the failure and fix tomorrow

**Comment by stefanpenner** [comment]
Looking at it now :)

**Comment by stefanpenner** [comment]
@pzuraq / @rwjblue we should be green! Sorry about that...

**Comment by pzuraq** [comment]
No worries! Published in v2.0.2

**Pull request merged**
